### ISSUE TITLE
Still have problem, using Passable Leaves

### ISSUE THREAD

**Issue by ghost** [Meldexun/BlockOverlayFix#2] opened 2022-08-08 12:31 UTC
https://imgur.com/a/4Ju9hXl

**Comment by ghost** [comment] 2022-08-08 13:09
It's a bug with vanilla minecraft, and we thought your mod fixing it

**Comment by Meldexun** [comment] 2022-08-08 17:39
Duplicate of #1
This is a bug in the passable leaves mod.

**Closed as completed by Meldexun** 2022-08-08 17:39 UTC
Labels: bug, duplicate
