### ISSUE TITLE
Incompatibility with PassableLeaves and fast graphics

### ISSUE THREAD

**Issue by ghost** [Meldexun/BlockOverlayFix#1] opened 2022-02-17 18:26 UTC
standing in leaves with Fast Graphics on...

![image](https://user-images.githubusercontent.com/71896090/154546457-e4badf7b-f8f4-4649-96e3-8dcef5372328.png)

**Comment by Meldexun** [comment] 2022-02-17 21:18
It works fine for me with Optifine installed (no other mods, no shaders, no resource packs).

**Comment by Meldexun** [comment] 2022-02-21 13:31
Please test what other mods, shaders or resource packs are needed to reproduce this and upload the log file.

As I am unable to reproduce the issue with just BlockOverlayFix and Optifine installed this looks to me like you didn't install the mod correctly or something else is causing the problem.

**Comment by ghost** [comment] 2022-02-22 18:45
Here's a modlist:
[mod-list_2022-02-22_11.39.06.txt](https://github.com/Meldexun/BlockOverlayFix/files/8119330/mod-list_2022-02-22_11.39.06.txt)

Here's the latest.log modlist:
[modlist ver 2.txt](https://github.com/Meldexun/BlockOverlayFix/files/8119356/modlist.ver.2.txt)


I have MixinBootstrap and BlockOverlayFix both installed.

### [Here's a video showing the issue](https://streamable.com/nfxas4)

Here's a trailer for the pack I've developed over the last two years: 
https://www.youtube.com/watch?v=X8EpwHdR62k&ab_channel=Finecraft%3AEnhancedSurvival

**Comment by Meldexun** [comment] 2022-02-22 18:57
I don't know how that trailer should help me.
Also I won't test the modpack for you (regarding the modlist you posted). If I would do that for everyone then I would have no time to do anything.

Besiades that this looks like a non-vanilla leaf block and if that is true this is not a bug of the BlockOverlayFix mod.

**Comment by ghost** [comment] 2022-02-22 19:17
> I don't know how that trailer should help me.

I just included it for fun, and to show I'm not some clueless kid complaining in the Issues section. Not sure why so many mod creators feel the need to be as rude as possible, but whatever.

----------------------------

After a quick test, I found that it's the Passable Leaves mod that causes the issue:

https://www.curseforge.com/minecraft/mc-mods/passable-leaves

This mod is very popular and critical to this modpack.

I'd still love to see compatability between the two if possible!

**Comment by Meldexun** [comment] 2022-02-22 19:59
> I just included it for fun, and to show I'm not some clueless kid complaining in the Issues section. Not sure why so many mod creators feel the need to be as rude as possible, but whatever.

Sorry I didn't want to be rude. But this is nonetheless an issue tracker and not a modpack advertisement forum and thus something like this isn't really useful here. Also I am not surprised that other devs think the same way.

Besides that if you want to show that you know what you are doing then you should try this:
- find a way to reproduce the bug with a minimal setup (if possible)
- mention all mods/shaders/config changes involved in the issue with the exact version numbers ('latest' is not good version as often players think they use the latest while they aren't actually)
- include a log file (it might not be needed but having it available at the beginning often makes thinks easier)

(Of course you don't have to do this. But having these infos available at the beginning usually makes resolving the issue a lot easier/faster and also shows that know what is important and what not)

---

I will look into compatibility with the passable leaves mod but this is not a priority and thus you shouldn't expect an update very soon.

**Comment by Meldexun** [comment] 2022-07-29 13:26
Actually this is a bug in the passable leaves mod. So it is up to them to fix this.

**Closed as completed by Meldexun** 2022-07-29 13:26 UTC
Labels: invalid

**Comment by ghost** [comment] 2022-08-08 13:09
It's a bug with vanilla minecraft, and we thought your mod fixing it
